[2023-06-13T11:33:26.072+0200] {processor.py:157} INFO - Started process (PID=68990) to work on /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:33:26.075+0200] {processor.py:826} INFO - Processing file /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-13T11:33:26.076+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:33:26.076+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:33:26.118+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:33:26.117+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-13T11:33:26.118+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:33:26.118+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-13T11:33:26.118+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:33:26.744+0200] {processor.py:179} INFO - Processing /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.672 seconds
[2023-06-13T11:35:40.151+0200] {processor.py:157} INFO - Started process (PID=69308) to work on /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:35:40.154+0200] {processor.py:826} INFO - Processing file /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-13T11:35:40.155+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:35:40.155+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:35:40.194+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:35:40.194+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-13T11:35:40.194+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:35:40.194+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-13T11:35:40.195+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:35:40.835+0200] {processor.py:179} INFO - Processing /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.685 seconds
[2023-06-13T11:39:09.493+0200] {processor.py:157} INFO - Started process (PID=69871) to work on /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:39:09.496+0200] {processor.py:826} INFO - Processing file /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-13T11:39:09.496+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:39:09.496+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:39:09.537+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:39:09.537+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-13T11:39:09.538+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:39:09.538+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-13T11:39:09.538+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:39:10.166+0200] {processor.py:179} INFO - Processing /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.674 seconds
[2023-06-13T11:46:30.746+0200] {processor.py:157} INFO - Started process (PID=71283) to work on /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:46:30.750+0200] {processor.py:826} INFO - Processing file /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-13T11:46:30.750+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:46:30.750+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:46:30.791+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:46:30.791+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-13T11:46:30.792+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:46:30.792+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-13T11:46:30.792+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:46:31.438+0200] {processor.py:179} INFO - Processing /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.693 seconds
[2023-06-13T11:48:56.434+0200] {processor.py:157} INFO - Started process (PID=71702) to work on /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:48:56.438+0200] {processor.py:826} INFO - Processing file /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-06-13T11:48:56.438+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:48:56.438+0200] {dagbag.py:541} INFO - Filling up the DagBag from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:48:56.483+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:48:56.482+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-06-13T11:48:56.483+0200] {logging_mixin.py:149} INFO - [2023-06-13T11:48:56.483+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-06-13T11:48:56.483+0200] {processor.py:838} WARNING - No viable dags retrieved from /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-06-13T11:48:57.165+0200] {processor.py:179} INFO - Processing /Users/simba/Documents/Converteo/cas_airflow1/env/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.732 seconds
